### PR TITLE
add chapters

### PR DESCRIPTION
**Pull request by kweav**
#### What changes are being implemented in this Pull Request?

Added the chapter and header structure as well as incorporated the first writing submissions

#### What was your approach?

- Added Rmd files
- Added Rmd files to _bookdown.yml

### Tell potential reviewers what kind of feedback you are soliciting.

Does this fit with the general ITCR structure? What should be done to better align it?

### CODE REVIEW

**Review by carriewright11 — APPROVED** [review]
This looks great! We might need to discuss the title a bit more with Juli and the group eventually- I know we've had a few different working titles - but we have plenty of time for that.

**Comment by carriewright11** [comment]
Looks like we have a couple of failed checks - I will take a look at the rendering failure. Could you please update our dictionary for the spelling? thanks!

**Comment by kweav** [comment]
Will do!

**Comment by carriewright11** [comment]
The render check fail suggests that some aspects might still be out-of-date. I am looking into this

**Comment by carriewright11** [comment]
Let's wait to merge till we get that fixed if we can

**Comment by kweav** [comment]
Thank you for looking into the render fail!

**Comment by carriewright11** [comment]
Can you please replace `leanbuild::set_knitr_image_path()` with `ottrpal::set_knitr_image_path()` in the rmd files? that is out-of-date and from the previous version of the template

**Comment by carriewright11** [comment]
Also if you see `leanbuild` anywhere else... should be changed to `ottrpal`

**Comment by kweav** [comment]
Thanks for pointing that block out! I forgot to add it to the new chapters. I'll search the repo to make sure `leanbuild` isn't mentioned elsewhere

**Pull request merged**
